const {chromium}=require('playwright');const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'no-preference'});const errors=[];page.on('pageerror',e=>errors.push(e.message));const report={environment:'Local Chrome headless, 1440x900 after warmup. Other hardware requires its own check.',samples:{}};
const measure=()=>page.evaluate(()=>new Promise(resolve=>{let previous=0;const values=[];const start=performance.now();function frame(t){if(previous)values.push(t-previous);previous=t;if(t-start<2000)requestAnimationFrame(frame);else {values.sort((a,b)=>a-b);resolve({frames:values.length,medianMs:+values[Math.floor(values.length/2)].toFixed(2),p95Ms:+values[Math.floor(values.length*.95)].toFixed(2),over50ms:values.filter(v=>v>50).length});}}requestAnimationFrame(frame);}));
try{await page.goto('http://127.0.0.1:5050');await page.locator('.tech-text[data-ready=true]').waitFor();await page.waitForTimeout(2300);let sample=measure();const bounds=await page.locator('.hero-copy').boundingBox();for(let i=0;i<6;i++){await page.mouse.move(bounds.x+20,bounds.y+120);await page.mouse.move(bounds.x+bounds.width-20,bounds.y+190,{steps:12});}report.samples.heroTechTextPatternWavesDotGrid=await sample;
await page.locator('.voltage-band').scrollIntoViewIfNeeded();await page.locator('.electric-logo[data-rendered=true]').waitFor();await page.waitForTimeout(800);sample=measure();for(let i=0;i<4;i++){await page.locator('.electric-emblem').hover({position:{x:30+i*30,y:40+i*20}});}report.samples.electricLogo=await sample;
await page.goto('http://127.0.0.1:5050/register');await page.locator('.rubber-segment').waitFor();sample=measure();for(let i=0;i<8;i++){await page.locator(i%2?'#register-tab':'#login-tab').click();await page.waitForTimeout(100);}report.samples.rubberSegmentAndBorderGlow=await sample;
// Mount the same real request trace through the app bridge, without creating a team or submission.
await page.evaluate(()=>{const host=document.createElement('div');host.className='commit-trace';document.querySelector('.auth-panel').prepend(host);window.traceProbe=App.activity(host,'Checking animation cadence…');});sample=measure();report.samples.thoughtLine=await sample;await page.evaluate(()=>{window.traceProbe.finish(true,'Animation check complete');delete window.traceProbe;});
assert.deepEqual(errors,[]);for(const [name,result] of Object.entries(report.samples)){assert.ok(result.p95Ms<35,name+' exceeded 35ms p95 on this machine');console.log(name,JSON.stringify(result));}fs.writeFileSync('artifacts/animation-performance.json',JSON.stringify(report,null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
