/* Run only against an isolated test database: this script resets the event. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
if (process.env.EXITCODE_E2E !== '1') throw new Error('Set EXITCODE_E2E=1 only for an isolated test server.');
const base = process.env.TEST_URL || 'http://127.0.0.1:5056';
const output = path.resolve(__dirname, '../artifacts'); fs.mkdirSync(output, {recursive:true});
(async () => {
 const browser = await chromium.launch({executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 const errors=[],checks=[];const check=(name)=>{checks.push(name);console.log('PASS',name);};
 const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});
 const adminContext=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});
 const page=await context.newPage(),admin=await adminContext.newPage();[page,admin].forEach(p=>p.on('pageerror',e=>errors.push(e.stack)));
 const shot=async(p,name,fullPage=true)=>p.screenshot({path:path.join(output,name+'.png'),fullPage});
 const state=async()=> (await admin.request.get(base+'/api/event-status')).json();
 async function eventAction(action){await admin.locator('[data-panel=controls]').click();await admin.locator(`[data-event-action=${action}]`).click();await admin.locator('#confirm-accept').click();await admin.waitForFunction(s=>document.getElementById('admin-workspace').dataset.eventStatus===s,({start:'LIVE',pause:'PAUSED',resume:'LIVE',end:'COMPLETED'})[action]);}
 async function enterArena(){await page.waitForURL(/\/(?:debug-)?arena(?:\?|$)/, {timeout:15000});await page.locator('#competition-start').click();if(await page.locator('#competition-fallback').isVisible())await page.locator('#competition-fallback').click();await page.locator('#competition-dialog').waitFor({state:'hidden'});}
 try {
  await admin.goto(base+'/admin/login');await admin.locator('#username').fill('admin');await admin.locator('#password').fill(process.env.ADMIN_PASSWORD||'exitcode0_admin_2026');await admin.locator('button[type=submit]').click();await admin.waitForURL(/\/admin/);
  assert.equal((await admin.request.post(base+'/api/admin/reset-event',{data:{confirmation:'RESET EVENT'}})).status(),200);await admin.reload();
  await page.goto(base);await page.waitForFunction(()=>!document.getElementById('home-standings').textContent.includes('Loading'));await shot(page,'home-desktop');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);check('Desktop homepage and real empty standings');
  const mobile=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.stack));for(const route of ['/','/register','/leaderboard']){await mp.goto(base+route);await mp.waitForTimeout(100);assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' overflow');await shot(mp,'mobile-'+(route.slice(1)||'home'));}check('Mobile home, registration, leaderboard without overflow');await mobile.close();
  await page.goto(base+'/register');await page.locator('#login-tab').click();assert.equal(await page.locator('#login-panel').isVisible(),true);await page.locator('#register-tab').click();await page.locator('#team-register-form button[type=submit]').click();assert.equal(await page.locator('#reg-member2').getAttribute('aria-invalid'),'true');
  await page.locator('#reg-name').fill('Phase One Review');await page.locator('#reg-member1').fill('Ada');await page.locator('#reg-member2').fill('Grace');await page.locator('#team-register-form button[type=submit]').click();await page.waitForURL(/\/waiting(?:-room)?$/);await shot(page,'waiting-room');check('Registration, segmented tabs, inline validation and lobby');
  const second=await browser.newContext();await second.request.post(base+'/register',{form:{name:'Second Review Team',member1:'Alan',member2:'Katherine'}});
  await admin.reload();await eventAction('start');await enterArena();await page.setViewportSize({width:1366,height:768});await page.waitForTimeout(200);await shot(page,'arena-1366',false);assert.equal(await page.evaluate(()=>document.body.scrollHeight>innerHeight),false);check('Admin start and lobby auto-entry; arena fits 1366x768');
  await page.locator('.line-number').nth(2).click();assert.equal(await page.locator('#error_location').inputValue(),'3');await page.locator('#cause').fill('The loop stops before processing the last element.');await page.waitForTimeout(500);await page.reload();await page.locator('#competition-start').click();if(await page.locator('#competition-fallback').isVisible())await page.locator('#competition-fallback').click();await page.waitForFunction(()=>document.getElementById('cause').value.includes('last element'));check('Clickable code lines and local draft recovery');
  await eventAction('pause');await page.evaluate(()=>EventClock.sync());await page.waitForFunction(()=>document.getElementById('commit-fix-btn').disabled);assert.equal((await page.request.post(base+'/api/submit-bug-fix',{data:{question_id:'Q01'}})).status(),403);await eventAction('resume');await page.evaluate(()=>EventClock.sync());await page.waitForFunction(()=>!document.getElementById('commit-fix-btn').disabled);check('Pause/resume locks submissions on client and server');
  await page.locator('#error_type').selectOption('Logical Error');await page.locator('#expected_output').fill('10');await page.locator('#correction').fill('Use range(len(numbers)) instead.');await page.route('**/api/submit-bug-fix',r=>r.abort());await page.locator('#commit-fix-btn').click();await page.waitForFunction(()=>document.getElementById('form-feedback-alert').textContent.includes('Unable to connect'));assert.match(await page.locator('#cause').inputValue(),/last element/);await page.unroute('**/api/submit-bug-fix');await page.locator('#commit-fix-btn').click();await page.waitForFunction(()=>document.getElementById('form-feedback-alert').textContent.includes('Submission recorded'));assert.equal(await page.locator('#submission-trace').getAttribute('data-success'),'true');check('Connection failure recovery and real server submission trace');
  await page.locator('#next-question').click();await page.waitForFunction(()=>document.getElementById('form-question-id').value==='Q02');await page.locator('#review-toggle').click();assert.equal(await page.locator('#review-toggle').getAttribute('aria-pressed'),'true');await page.goBack();await page.waitForFunction(()=>document.getElementById('form-question-id').value==='Q01');await page.goForward();await page.waitForFunction(()=>document.getElementById('form-question-id').value==='Q02');check('Instant question navigation, review markers, back/forward');
  if(await page.evaluate(()=>!!document.fullscreenElement))await page.evaluate(()=>document.exitFullscreen());await page.waitForFunction(()=>!document.getElementById('fullscreen-reminder').hidden);await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));assert.equal((await page.request.post(base+'/api/activity',{data:{event_type:'tab_hidden'}})).status(),200);check('Fullscreen recovery and advisory activity');
  await page.goto(base+'/leaderboard');await page.waitForFunction(()=>document.querySelectorAll('#leaderboard-table-body tr').length===2);await shot(page,'leaderboard');assert.match(await page.locator('.own-team').first().textContent(),/Phase One/);check('Live leaderboard and own-team highlight');
  await admin.reload();await admin.locator('[data-panel=submissions]').click();await admin.locator('[data-submission-view]').first().click();await admin.locator('.admin-override-form input[name=new_score]').fill('18');await admin.locator('.admin-override-form input[name=reason]').fill('Browser test score review');await admin.locator('.admin-override-form button[type=submit]').click();await admin.waitForTimeout(250);await admin.locator('[data-panel=security]').click();await shot(admin,'security-monitor');check('Organizer submission review, score adjustment and security monitor');
  await admin.locator('[data-panel=overview]').click();await shot(admin,'admin-overview');
  for(const route of ['/admin/export/teams.csv','/admin/export/results.csv'])assert.equal((await admin.request.get(base+route)).status(),200);check('CSV exports');
  await eventAction('end');await page.goto(base+'/result');assert.match(await page.locator('h1').textContent(),/Debugging complete/);await shot(page,'results-provisional');
  await admin.locator('[data-panel=quiz]').click();await admin.locator('[data-quiz-action=open]').click();await admin.locator('#confirm-accept').click();await admin.waitForFunction(()=>document.getElementById('admin-quiz-status').textContent==='OPEN');
  const scoreBefore=(await(await page.request.get(base+'/api/team-progress')).json()).debug_score;
  await page.goto(base+'/quiz');await page.locator('#quiz-start').click();await page.locator('#quiz-play').waitFor({state:'visible'});await shot(page,'quiz');for(let i=0;i<10;i++){await page.locator('#quiz-options input').first().check();await page.locator('#quiz-lock').click();if(i<9)await page.waitForFunction(n=>document.getElementById('quiz-progress-label').textContent.startsWith('QUESTION '+String(n).padStart(2,'0')+' /'),i+2);}
  await page.locator('#quiz-finish').waitFor({state:'visible'});const scoreAfter=(await(await page.request.get(base+'/api/team-progress')).json()).debug_score;assert.equal(scoreBefore,scoreAfter);check('Separate quiz complete; official debugging score unchanged');
  await admin.locator('[data-panel=rankings]').click();await admin.locator('#admin-publish-results').click();await admin.locator('#confirm-accept').click();await admin.waitForFunction(()=>document.getElementById('admin-publish-results').textContent.includes('published'));await page.goto(base+'/result');await shot(page,'results-final');assert.equal(await page.locator('.results-winners').isVisible(),true);check('Final results publication and podium');
  await admin.locator('[data-panel=settings]').click();await admin.locator('#admin-reset-open').click();await admin.locator('#reset-confirmation-input').fill('RESET');assert.equal(await admin.locator('#admin-reset-confirm').isDisabled(),true);await admin.locator('#reset-confirmation-input').fill('RESET EVENT');await admin.locator('#admin-reset-confirm').click();await admin.waitForTimeout(200);assert.equal((await state()).event_status,'WAITING');assert.equal((await(await admin.request.get(base+'/api/leaderboard-data')).json()).leaderboard.length,0);check('Exact typed reset removes test event data');
  assert.deepEqual(errors,[]);check('No browser JavaScript errors');
  fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({checks,errors},null,2));
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
