const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
try{
 await p.goto('http://127.0.0.1:5050');const editor=p.locator('.editor-demo');await p.waitForFunction(()=>document.querySelector('.editor-demo').dataset.demoStage==='passed');
 const box=await editor.boundingBox();const old=JSON.parse(fs.readFileSync('artifacts/demo-scope-geometry.json'));assert.deepEqual(box,old);for(const [selector,name] of [['.hero-copy','title'],['#event','event']]){const now=await p.locator(selector).screenshot();assert.ok(now.equals(fs.readFileSync('artifacts/demo-scope-'+name+'-before.png')),'Surrounding '+name+' changed');}console.log('PASS unchanged demo geometry and surrounding homepage pixels');
 assert.equal(await editor.evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(11, 11, 13)');assert.equal(await editor.locator('.border-glow-card--strong').count(),1);assert.equal(await p.locator('#demo-return-value').textContent(),'0');assert.equal(await editor.getAttribute('data-demo-paused'),'true');await p.waitForTimeout(500);assert.equal(await editor.getAttribute('data-demo-stage'),'passed');console.log('PASS red/black palette, visible glow and static reduced-motion state');
 await p.emulateMedia({reducedMotion:'no-preference'});await p.locator('#demo-toggle').click(); // Pause immediately to check the current frame is held.
 const held=await p.locator('.demo-run-progress').evaluate(el=>getComputedStyle(el).transform);const stage=await editor.getAttribute('data-demo-stage');await p.waitForTimeout(450);assert.equal(await p.locator('.demo-run-progress').evaluate(el=>getComputedStyle(el).transform),held);assert.equal(await editor.getAttribute('data-demo-stage'),stage);await p.locator('#demo-toggle').click();console.log('PASS pause/resume freezes animations and stage clock');
 await p.waitForFunction(()=>document.querySelector('.editor-demo').dataset.demoStage==='scanning',{},{timeout:7000});const scan1=await p.locator('.demo-scan-cursor').evaluate(el=>getComputedStyle(el).transform);await p.waitForTimeout(250);assert.notEqual(await p.locator('.demo-scan-cursor').evaluate(el=>getComputedStyle(el).transform),scan1);console.log('PASS live source scan movement');
 await p.waitForFunction(()=>document.querySelector('.editor-demo').dataset.demoStage==='diagnostic',{},{timeout:5000});assert.match(await p.locator('#demo-status').textContent(),/Division by zero/);await p.waitForFunction(()=>document.querySelector('.editor-demo').dataset.demoStage==='fixing',{},{timeout:5000});await p.waitForFunction(()=>document.getElementById('demo-return-value').textContent==='0');await p.waitForFunction(()=>document.querySelector('.editor-demo').dataset.demoStage==='testing',{},{timeout:5000});await p.waitForFunction(()=>document.querySelector('.editor-demo').dataset.demoStage==='passed',{},{timeout:5000});assert.equal(await p.locator('#demo-status-badge').textContent(),'PASSED');console.log('PASS complete fault → fix → tests → passed sequence');
 await p.locator('#demo-toggle').click();await editor.screenshot({path:'artifacts/demo-red-animated.png'});await p.locator('#demo-toggle').click();await p.locator('.closing-cta').scrollIntoViewIfNeeded();await p.waitForFunction(()=>document.querySelector('.editor-demo').dataset.demoPaused==='true');const offscreen=await editor.getAttribute('data-demo-stage');await p.waitForTimeout(350);assert.equal(await editor.getAttribute('data-demo-stage'),offscreen);await editor.scrollIntoViewIfNeeded();await p.waitForFunction(()=>document.querySelector('.editor-demo').dataset.demoPaused==='false');console.log('PASS offscreen suspension and resume');
 await p.setViewportSize({width:390,height:844});await p.emulateMedia({reducedMotion:'reduce'});await editor.scrollIntoViewIfNeeded();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await editor.screenshot({path:'artifacts/demo-red-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS mobile layout and no React/WebGL/browser errors');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
